### importing data set from files

In [4]:
from google.colab import files
uploaded = files.upload()

Saving orders.csv to orders.csv

In [5]:
 import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [14]:
order_details = pd.read_csv("order_details.csv")
orders = pd.read_csv("orders.csv")
pizza_types= pd.read_csv("pizza_types.csv", encoding='latin1')
pizzas = pd.read_csv("pizzas.csv", encoding= 'latin1')

In [15]:
order_details

       order_details_id  order_id       pizza_id  quantity
0                     1         1     hawaiian_m         1
1                     2         2  classic_dlx_m         1
2                     3         2  five_cheese_l         1
3                     4         2    ital_supr_l         1
4                     5         2     mexicana_m         1
...                 ...       ...            ...       ...
48615             48616     21348  ckn_alfredo_m         1
48616             48617     21348  four_cheese_l         1
48617             48618     21348   napolitana_s         1
48618             48619     21349     mexicana_l         1
48619             48620     21350      bbq_ckn_s         1

[48620 rows x 4 columns]

### checking the data ramdomly

In [21]:
orders

       order_id        date      time
0             1  2015-01-01  11:38:36
1             2  2015-01-01  11:57:40
2             3  2015-01-01  12:12:28
3             4  2015-01-01  12:16:31
4             5  2015-01-01  12:21:30
...         ...         ...       ...
21345     21346  2015-12-31  20:51:07
21346     21347  2015-12-31  21:14:37
21347     21348  2015-12-31  21:23:10
21348     21349  2015-12-31  22:09:54
21349     21350  2015-12-31  23:02:05

[21350 rows x 3 columns]

In [16]:
orders

       order_id        date      time
0             1  2015-01-01  11:38:36
1             2  2015-01-01  11:57:40
2             3  2015-01-01  12:12:28
3             4  2015-01-01  12:16:31
4             5  2015-01-01  12:21:30
...         ...         ...       ...
21345     21346  2015-12-31  20:51:07
21346     21347  2015-12-31  21:14:37
21347     21348  2015-12-31  21:23:10
21348     21349  2015-12-31  22:09:54
21349     21350  2015-12-31  23:02:05

[21350 rows x 3 columns]

In [22]:
pizzas

         pizza_id pizza_type_id size  price
0       bbq_ckn_s       bbq_ckn    S  12.75
1       bbq_ckn_m       bbq_ckn    M  16.75
2       bbq_ckn_l       bbq_ckn    L  20.75
3      cali_ckn_s      cali_ckn    S  12.75
4      cali_ckn_m      cali_ckn    M  16.75
..            ...           ...  ...    ...
91  spinach_fet_m   spinach_fet    M  16.00
92  spinach_fet_l   spinach_fet    L  20.25
93   veggie_veg_s    veggie_veg    S  12.00
94   veggie_veg_m    veggie_veg    M  16.00
95   veggie_veg_l    veggie_veg    L  20.25

[96 rows x 4 columns]

In [38]:
dataset.shape

(48620, 12)

In [28]:
##Step 1: Merge order_details with pizzas on 'pizza_id'
merged1 = pd.merge(order_details, pizzas, on='pizza_id', how='left')

# Step 2: Merge the result with pizza_types on 'pizza_type_id'
merged2 = pd.merge(merged1, pizza_types, on='pizza_type_id', how='left')

# Step 3: Merge with orders on 'order_id'
final_merged_dataset = pd.merge(merged2, orders, on='order_id', how='left')

# Save the final merged dataset to a new CSV file
final_merged_dataset.to_csv("merged_pizza_dataset.csv", index=False)

In [46]:
dataset = pd.read_csv("merged_pizza_dataset.csv")

EXPLORING THE MERGED_pizza_dataset

In [50]:
dataset.head()

,order_details_id,order_id,pizza_id,quantity,pizza_type_id,size,price,name,category,ingredients,date,time
0,1,1,hawaiian_m,1,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01,11:38:36
1,2,2,classic_dlx_m,1,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01,11:57:40
2,3,2,five_cheese_l,1,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01,11:57:40
3,4,2,ital_supr_l,1,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01,11:57:40
4,5,2,mexicana_m,1,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01,11:57:40

In [52]:
dataset.shape

(48620, 12)

In [53]:
dataset.isna().sum()

order_details_id    0
order_id            0
pizza_id            0
quantity            0
pizza_type_id       0
size                0
price               0
name                0
category            0
ingredients         0
date                0
time                0
dtype: int64

##  Convert date/time for time-based analysi

In [54]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   pizza_type_id     48620 non-null  object
 5   size              48620 non-null  object
 6   price             48620 non-null  float64
 7   name              48620 non-null  object
 8   category          48620 non-null  object
 9   ingredients       48620 non-null  object
 10  date              48620 non-null  object
 11  time              48620 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.5+ MB

In [58]:
dataset["date"] = pd.to_datetime(dataset["date"])
dataset['time'] = pd.to_datetime(dataset["time"]) ## converting data and time in object data type to datetime data type
dataset['hour'] = dataset['time'].dt.hour
dataset['weekday'] = dataset['date'].dt.day_name()
dataset['month'] = dataset['date'].dt.month_name()

In [59]:
dataset

,order_details_id,order_id,pizza_id,quantity,pizza_type_id,size,price,name,category,ingredients,date,time,hour,weekday,month
0,1,1,hawaiian_m,1,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",2015-01-01,2025-05-10 11:38:36,11,Thursday,January
1,2,2,classic_dlx_m,1,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2015-01-01,2025-05-10 11:57:40,11,Thursday,January
2,3,2,five_cheese_l,1,five_cheese,L,18.50,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",2015-01-01,2025-05-10 11:57:40,11,Thursday,January
3,4,2,ital_supr_l,1,ital_supr,L,20.75,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",2015-01-01,2025-05-10 11:57:40,11,Thursday,January
4,5,2,mexicana_m,1,mexicana,M,16.00,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-01-01,2025-05-10 11:57:40,11,Thursday,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48615,48616,21348,ckn_alfredo_m,1,ckn_alfredo,M,16.75,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A...",2015-12-31,2025-05-10 21:23:10,21,Thursday,December
48616,48617,21348,four_cheese_l,1,four_cheese,L,17.95,The Four Cheese Pizza,Veggie,"Ricotta Cheese, Gorgonzola Piccante Cheese, Mo...",2015-12-31,2025-05-10 21:23:10,21,Thursday,December
48617,48618,21348,napolitana_s,1,napolitana,S,12.00,The Napolitana Pizza,Classic,"Tomatoes, Anchovies, Green Olives, Red Onions,...",2015-12-31,2025-05-10 21:23:10,21,Thursday,December
48618,48619,21349,mexicana_l,1,mexicana,L,20.25,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",2015-12-31,2025-05-10 22:09:54,22,Thursday,December
48619,48620,21350,bbq_ckn_s,1,bbq_ckn,S,12.75,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",2015-12-31,2025-05-10 23:02:05,23,Thursday,December

In [60]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   pizza_type_id     48620 non-null  object
 5   size              48620 non-null  object
 6   price             48620 non-null  float64
 7   name              48620 non-null  object
 8   category          48620 non-null  object
 9   ingredients       48620 non-null  object
 10  date              48620 non-null  datetime64[ns]
 11  time              48620 non-null  datetime64[ns]
 12  hour              48620 non-null  int32
 13  weekday           48620 non-null  object
 14  month             48620 non-null  object
dtypes: datetime64[ns](2), float64(1), int32(1), int64(3), object(8)
memory usage: 5.4+ MB


# add revenue column

In [61]:
dataset['revenue'] = dataset['price'] * dataset['quantity']

## 1. Total revenue/sales

In [64]:
total_revenue = dataset['revenue'].sum()

In [65]:
total_revenue

np.float64(817860.05)

## 2. Total quantity sold

In [66]:
total_quantity = dataset['quantity'].sum()

In [67]:
total_quantity

np.int64(49574)

## 3. Total order

In [68]:
total_order = dataset['order_id'].nunique()

In [69]:
total_order

21350


# 4. How many pizza types

In [70]:
total_pizza_types = dataset['pizza_type_id'].nunique()

In [71]:
total_pizza_types

32

## 5 Average pizza price

In [72]:
average_pizza_price = dataset[['pizza_id', 'price']].drop_duplicates()['price'].mean()

In [73]:
average_pizza_price

np.float64(16.506043956043957)

# 6. Peak hours of sales

In [74]:
peak_sales_hours = dataset.groupby('hour')['revenue'].sum().sort_values(ascending=False)

In [75]:
peak_sales_hours

hour
12    111877.90
13    106065.70
18     89296.85
17     86237.45
19     72628.90
16     70055.40
14     59201.40
20     58215.40
15     52992.30
11     44935.80
21     42029.80
22     22815.15
23      1121.35
10       303.65
9         83.00
Name: revenue, dtype: float64

# 7. Total sales by weekday

In [78]:
sales_by_weekday = dataset.groupby('weekday')['revenue'].sum().sort_values(ascending=False)

In [79]:
sales_by_weekday

weekday
Friday       136073.90
Thursday     123528.50
Saturday     123182.40
Wednesday    114408.40
Tuesday      114133.80
Monday       107329.55
Sunday        99203.50
Name: revenue, dtype: float64

# 8. Top 5 bestselling pizzas

In [80]:
top_5_pizzas = dataset.groupby('pizza_id')['quantity'].sum().sort_values(ascending=False).head(5)

In [81]:
top_5_pizzas

pizza_id
big_meat_s       1914
thai_ckn_l       1410
five_cheese_l    1409
four_cheese_l    1316
classic_dlx_m    1181
Name: quantity, dtype: int64

# 9. Sales made in each month

In [82]:
monthly_sales = dataset.groupby('month')['revenue'].sum()

In [83]:
monthly_sales

month
April        68736.80
August       68278.25
December     64701.15
February     65159.60
January      69793.30
July         72557.90
June         68230.20
March        70397.10
May          71402.75
November     70395.35
October      64027.60
September    64180.05
Name: revenue, dtype: float64


# 10. Least performing pizza types

In [84]:
least_selling_pizzas = dataset.groupby('pizza_type_id')['quantity'].sum().sort_values().head(5)

In [85]:
least_selling_pizzas

pizza_type_id
brie_carre      490
mediterraneo    934
calabrese       937
spinach_supr    950
soppressata     961
Name: quantity, dtype: int64